version: '3.5'
services:
  node1:
    container_name: node1
    hostname: node1
    build:
      context: ./ubuntu
      args:
        - UID=$UID
        - GID=$GID
    volumes: 
      - ./share:/home/ubuntu/share
    networks:
      lan1-2:
        ipv4_address: 172.20.0.10
      lan1-3:
        ipv4_address: 172.21.0.10
      lan1-4:
        ipv4_address: 172.22.0.10
      lan1-5:
        ipv4_address: 172.23.0.10
    cap_add:
      - NET_ADMIN
    tty: true
  node2:
    container_name: node2
    hostname: node2
    build:
      context: ./ubuntu
      args:
        - UID=$UID
        - GID=$GID
    volumes: 
      - ./share:/home/ubuntu/share
    networks:
      lan1-2:
        ipv4_address: 172.20.0.20
      lan2-3:
        ipv4_address: 172.24.0.20
      lan2-4:
        ipv4_address: 172.25.0.20
      lan2-5:
        ipv4_address: 172.26.0.20
    cap_add:
      - NET_ADMIN
    tty: true
  node3:
    container_name: node3
    hostname: node3
    build:
      context: ./ubuntu
      args:
        - UID=$UID
        - GID=$GID
    volumes: 
      - ./share:/home/ubuntu/share
    networks:
      lan1-3:
        ipv4_address: 172.21.0.30
      lan2-3:
        ipv4_address: 172.24.0.30
      lan3-4:
        ipv4_address: 172.27.0.30
      lan3-5:
        ipv4_address: 172.28.0.30
    cap_add:
      - NET_ADMIN
    tty: true
  node4:
    container_name: node4
    hostname: node4
    build:
      context: ./ubuntu
      args:
        - UID=$UID
        - GID=$GID
    volumes: 
      - ./share:/home/ubuntu/share
    networks:
      lan1-4:
        ipv4_address: 172.22.0.40
      lan2-4:
        ipv4_address: 172.25.0.40
      lan3-4:
        ipv4_address: 172.27.0.40
      lan4-5:
        ipv4_address: 172.29.0.40
    cap_add:
      - NET_ADMIN
    tty: true
  node5:
    container_name: node5
    hostname: node5
    build:
      context: ./ubuntu
      args:
        - UID=$UID
        - GID=$GID
    volumes: 
      - ./share:/home/ubuntu/share
    networks:
      lan1-5:
        ipv4_address: 172.23.0.50
      lan2-5:
        ipv4_address: 172.26.0.50
      lan3-5:
        ipv4_address: 172.28.0.50
      lan4-5:
        ipv4_address: 172.29.0.50
    cap_add:
      - NET_ADMIN
    tty: true
networks:
  lan1-2:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
  lan1-3:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
  lan1-4:
    ipam:
      driver: default
      config:
        - subnet: 172.22.0.0/16
  lan1-5:
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16
  lan2-3:
    ipam:
      driver: default
      config:
        - subnet: 172.24.0.0/16
  lan2-4:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
  lan2-5:
    ipam:
      driver: default
      config:
        - subnet: 172.26.0.0/16
  lan3-4:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16
  lan3-5:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  lan4-5:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
